substitutions:
  devicename: fastled
  platform: ESP8266
#  board: nodemcuv2
  board: esp01_1m
  devicedescr: FastLED Strip
  strip_num_leds: '100'
  strip_pin: GPIO0
  alive_pin: GPIO2

esphome:
  name: ${devicename}

esp8266:
  board: ${board}
  framework:
    version: 2.7.4

packages:
  base_settings: !include common/base_settings.yaml
  wifi: !include common/network.yaml
  uptime: !include common/uptime.yaml
  wifi_info: !include common/wifi_info.yaml
  fastled_strip: !include common/fastled_strip.yaml
  alive_led: !include common/alive_led.yaml
