substitutions:
  devicename: fastled
  platform: ESP8266
  board: esp01_1m
  devicedescr: FastLED Strip
  strip_num_leds: '300'
  strip_rgb_order: GRB
  strip_pin: GPIO0
  alive_pin: GPIO2

esphome:
  name: ${devicename}
  
esp8266:
  board: ${board}

packages:
  base_settings: !include packages/base_settings.yaml
  wifi: !include packages/network.yaml
  uptime: !include packages/uptime.yaml
  wifi_info: !include packages/wifi_info.yaml
  fastled_strip: !include packages/neopixel_strip.yaml
  alive_led: !include packages/alive_led.yaml
