substitutions:
  devicename: hall_fastled_strip
  platform: ESP8266
  board: nodemcuv2
#  board: esp01_1m
  devicedescr: FastLED Strip
  strip_num_leds: '300'
  strip_pin: GPIO4
  alive_pin: GPIO2

esphome:
  name: ${devicename}

esp8266:
  board: ${board}
  framework:
    version: 2.7.4

packages:
  base_settings: !include packages/base_settings.yaml
  wifi: !include packages/network.yaml
  uptime: !include packages/uptime.yaml
  wifi_info: !include packages/wifi_info.yaml
  fastled_strip: !include packages/fastled_strip.yaml
  alive_led: !include packages/alive_led.yaml
