substitutions:
  devicename: test_led_strip
  platform: ESP8266
  board: nodemcuv2
#  board: esp01_1m
  devicedescr: LED Strip
  strip_num_leds: '30'
  strip_rgb_order: GRB
  strip_pin: GPIO4
  alive_pin: GPIO2

esphome:
  name: ${devicename}

esp8266:
  board: ${board}

web_server:
  port: 80

packages:
  wifi: !include packages/network.yaml
  base_settings: !include packages/base_settings.yaml
#  uptime: !include packages/uptime.yaml
#  wifi_info: !include packages/wifi_info.yaml
  fastled_strip: !include packages/neopixel_strip.yaml
  alive_led: !include packages/alive_led.yaml

logger:
  logs:
    sensor: ERROR
    text_sensor: ERROR