substitutions:
  devicename: window_led
  devicedescr: Гирлянда
  platform: ESP8266
  board: esp01_1m

esphome:
  name: ${devicename}
  platform: ${platform}
  board: ${board}
  
logger:

ota:
  password: room414415

web_server:
  port: 80

packages:
  wifi: !include packages/network.yaml
  uptime: !include packages/uptime.yaml
  wifi_info: !include packages/wifi_info.yaml

switch:
  - platform: gpio
    name: ${devicedescr} Relay
    id: relay
    pin: 2
    restore_mode: ALWAYS_ON
