esphome:
  includes:
    - custom/LedStripEffects
  on_boot:
    priority: 600
    then:
      - light.control:
          id: neopixel_strip
          state: on

custom_component:
- lambda: |-
    auto my_custom = new Nezumikun::LedStripEffectsComponent();
    return {my_custom};
  components:
  - id: strip

light:
  - platform: neopixelbus
    variant: WS2812
    pin: ${strip_pin}
    num_leds: ${strip_num_leds}
    type: ${strip_rgb_order}
    name: "WS2812B Light"
    id: neopixel_strip
    on_turn_on:
      - light.control:
          id: neopixel_strip
          effect: "Demo"
    effects:
      - addressable_lambda:
          name: "Demo"
          update_interval: 10ms
          lambda: |-
            auto ptr = id(strip);
            static_cast<Nezumikun::LedStripEffectsComponent*>(ptr)->demo(it, initial_run);
      - addressable_lambda:
          name: "Rainbow"
          update_interval: 10ms
          lambda: |-
            auto ptr = id(strip);
            static_cast<Nezumikun::LedStripEffectsComponent*>(ptr)->rainbow(it, initial_run);
      - addressable_lambda:
          name: "Color Cycle"
          update_interval: 10ms
          lambda: |-
            auto ptr = id(strip);
            static_cast<Nezumikun::LedStripEffectsComponent*>(ptr)->color_cycle(it, initial_run);
      - addressable_lambda:
          name: "Confetti"
          update_interval: 10ms
          lambda: |-
            auto ptr = id(strip);
            static_cast<Nezumikun::LedStripEffectsComponent*>(ptr)->confetti(it, initial_run);
      - addressable_lambda:
          name: "Sinelon"
          update_interval: 10ms
          lambda: |-
            auto ptr = id(strip);
            static_cast<Nezumikun::LedStripEffectsComponent*>(ptr)->sinelon(it, initial_run);
      - addressable_lambda:
          name: "Juggle"
          update_interval: 10ms
          lambda: |-
            auto ptr = id(strip);
            static_cast<Nezumikun::LedStripEffectsComponent*>(ptr)->juggle(it, initial_run);
      - addressable_lambda:
          name: "Beats"
          update_interval: 10ms
          lambda: |-
            auto ptr = id(strip);
            static_cast<Nezumikun::LedStripEffectsComponent*>(ptr)->beats(it, initial_run);
      - addressable_lambda:
          name: "Noise"
          update_interval: 10ms
          lambda: |-
            auto ptr = id(strip);
            static_cast<Nezumikun::LedStripEffectsComponent*>(ptr)->noise(it, initial_run);
