text_sensor:
  - platform: template
    name: ${devicedescr} Uptime
    id: ${devicename}_uptime_human
    icon: mdi:clock-start

sensor:
  - platform: uptime
    id: uptime_sensor
    update_interval: 60s
    internal: True
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: ${devicename}_uptime_human
            state: !lambda |-
              int seconds = round(id(uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              static char res[50];
              if (days > 0) {
                sprintf(res, "%i д. %i ч. %i мин.", days, hours, minutes);
              }
              else if (hours > 0) {
                sprintf(res, "%i ч. %i мин.", hours, minutes);
              }
              else {
                sprintf(res, "%i мин.", minutes);
              }
              return res;
